FROM node:20-alpine

WORKDIR /app

COPY packages/server/package*.json ./

RUN npm install

RUN npm install -g @nestjs/cli

COPY packages/server/src ./src
COPY packages/server/nest-cli.json ./nest-cli.json
COPY packages/server/tsconfig*.json ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
