FROM node:20-alpine

WORKDIR /app

COPY packages/www/package*.json ./

RUN npm install

COPY packages/www/src ./src
COPY packages/www/index.html ./index.html
COPY packages/www/vite.config.ts ./vite.config.ts
COPY packages/www/tsconfig*.json ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
